In [ ]:
import numpy as np # импортируем библиотеку
from scipy.linalg import solve
import matplotlib.pyplot as plt
import scipy.linalg as sl
import sympy

длина стороны равна 2
kx=ky=1

In [ ]:
adiag = np.array([2., 4., 4., 4., 2.,
                     4., 8., 8., 8., 4.,
                     4., 8., 6., 4., 2.,
                     4., 8., 4.,
                     4., 8., 4.,
                     4., 8., 4.,
                     4., 8., 4.,
                     2., 4., 2])
altr = np.array([-1., -1., -1., -1., -1., -2., -2., -2., -2., -2., -2., -1., -2., -1., -2., -2., -2., -2., -2., -1., -1., -1., -1., -2., -2., -1., -2., -1.,
                    -2., -2., -1., -2., -1., -2., -2., -1., -2., -1., -2., -2., -1., -2., -1., -2., -1., -1., -1.])
jptr = np.array([1, 2, 3, 4, 1, 2, 6, 3, 7, 4, 8, 5, 9, 6, 7, 11, 8, 12, 9, 13, 10, 14, 11, 12, 16, 13, 17,
                    16, 17, 19, 18, 20, 19, 20, 22, 21, 23, 22, 23, 25, 24, 26, 25, 26, 28, 27, 29])
#iptr = np.array([1, 2, 3, 4, 5, 6, 8, 10, 12, 14, 15, 17, 19, 21, 23, 24, 26, 28, 29, 31, 33, 34, 35, 37, 39, 40, 43, 44, 46])

iptr = np.array([1, 2, 3, 4, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 16, 16, 17,
                 17, 18, 19, 19, 20, 20, 21, 22, 22, 23, 23, 24, 25, 25, 26, 26, 27, 28, 28, 29, 29])

n = 30
len(iptr)

47

In [ ]:
l = 75.
q=150.
Tg=25.
lg=10.

In [ ]:
# @title Текст заголовка по умолчанию
v2 = np.array([q/2, q,q,q,q/2+Tg*lg/2,0,0,0,0,Tg*2*lg/2,0,0,Tg*2*lg/2,Tg*2*lg/2,Tg*2*lg/2,0,0,Tg*2*lg/2,0,0,Tg*2*lg/2,0,0,Tg*2*lg/2,0,0,Tg*2*lg/2,0,0,Tg*lg/2])
print(v2)
A = np.zeros((30,30))

for i in range(30):
  A[i][i] = adiag[i]*l/2

for k in range(len(altr)):
    A[iptr[k]][jptr[k]-1]=altr[k]*l/2
    A[jptr[k]-1][iptr[k]]=altr[k]*l/2
print('\n'.join('\t'.join(map(str, row)) for row in A))

A[4][4]+=lg/2

b=v2

#np.linalg.solve(A, v2)


[ 75. 150. 150. 150. 200.   0.   0.   0.   0. 250.   0.   0. 250. 250.
 250.   0.   0. 250.   0.   0. 250.   0.   0. 250.   0.   0. 250.   0.
   0. 125.]
75.0	-37.5	0.0	0.0	0.0	-37.5	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
-37.5	150.0	-37.5	0.0	0.0	0.0	-75.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
0.0	-37.5	150.0	-37.5	0.0	0.0	0.0	-75.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
0.0	0.0	-37.5	150.0	-37.5	0.0	0.0	0.0	-75.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
0.0	0.0	0.0	-37.5	75.0	0.0	0.0	0.0	0.0	-37.5	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
-37.5	0.0	0.0	0.0	0.0	150.0	-75.0	0.0	0.0	0.0	-37.5	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
0.0	-75.0	0.0	0.0	0.0	-75.0	300.0	-75.0	0.0	0.0	0.0	-75.0	0.0	0.0	0.0	0.0	0.0	0.0	0.

In [ ]:
v2

array([ 75., 150., 150., 150., 200.,   0.,   0.,   0.,   0., 250.,   0.,
         0., 250., 250., 250.,   0.,   0., 250.,   0.,   0., 250.,   0.,
         0., 250.,   0.,   0., 250.,   0.,   0., 125.])

In [ ]:
t=solve(A,v2)
t.round(1)

array([40.1, 40.1, 40.8, 41.3, 40.9, 38. , 38.4, 39.4, 40.4, 41.7, 37. ,
       37.5, 39.6, 40.9, 41.2, 35. , 35.5, 37.2, 34.3, 34.8, 36.7, 33.6,
       34.1, 36. , 32.9, 33.4, 35.2, 32.2, 32.6, 34.2])

In [ ]:
L=np.linalg.cholesky(A)
#y=solve(L, v2)
y=np.linalg.solve(L, v2)
H=L.T
np.linalg.lstsq(H, y, rcond=-1)
#solve(L.T, y)

(array([630.9989267 , 628.84120554, 621.54126264, 605.70894921,
        570.        , 631.15664786, 629.41231642, 623.8074479 ,
        613.6472671 , 604.95771746, 634.80303191, 633.84396437,
        630.62894545, 620.11495382, 615.86966897, 640.36755103,
        640.53156369, 641.68922768, 645.60404482, 646.2255117 ,
        648.39817121, 649.59760485, 650.36826707, 652.78576709,
        652.04984045, 652.86418466, 655.34169632, 652.87338762,
        653.69693479, 656.18598222]),
 array([], dtype=float64),
 30,
 array([22.20240101, 21.56662282, 20.57999781, 19.66448743, 18.49606155,
        17.1140712 , 17.05973744, 15.69163345, 14.73917344, 14.23879204,
        13.70703483, 13.35504102, 13.04022657, 12.8511167 , 12.52303156,
        12.39261646, 12.2310291 , 11.51221494, 11.26986692, 10.95203932,
        10.01779352,  9.47746661,  8.71765861,  7.95729699,  7.63813679,
         7.50071751,  5.66882802,  4.59831414,  2.45145257,  0.38363845]))

In [ ]:
reduced_echlon_form = sympy.Matrix(A).rref()
reduced_echlon_form


(Matrix([
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [ ]:

def bubble_max_row(m, k):
    """Replace m[col] row with the one of the underlying rows with the modulo greatest first element.
    :param m: numpy matrix
    :param k: number of the step in forward trace
    :return: None. Function changes the matrix structure.
    """
    ind = k + np.argmax(np.abs(m[k:, k]))
    if ind != k:
        m[k, :], m[ind, :] = np.copy(m[ind, :]), np.copy(m[k, :])


def solve_gauss(m):
    """Solve linear equations system with gaussian method.
    :param m: numpy matrix
    :return: None
    """
    n = m.shape[0]
    # forward trace
    for k in range(n - 1):
        bubble_max_row(m, k)
        for i in range(k + 1, n):
            # modify row
            frac = m[i, k] / m[k, k]
            m[i, :] -= m[k, :] * frac

    # check modified system for nonsingularity
    if is_singular(m):
        print('The system has infinite number of answers...')
        return

    # backward trace
    x = np.matrix([0.0 for i in range(n)]).T
    for k in range(n - 1, -1, -1):
        x[k, 0] = (m[k, -1] - m[k, k:n] * x[k:n, 0]) / m[k, k]

    # Display results
    print(x)


def is_singular(m):
    """Check matrix for nonsingularity.
    :param m: matrix (list of lists)
    :return: True if system is nonsingular
    """
    return np.any(np.diag(m) == 0)


m = A
solve_gauss(m)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
