In [ ]:
import math
import numpy as np
import pandas as pd
from sympy import *
x = symbols('x')

In [ ]:
T_q=150
a_g=10
T_g=40
K=72
L=7.5
R=1
H=L/2
S=math.pi*R**2
P=2*math.pi*R

In [ ]:
x_2=[0, H/2, H, 3*H/2, 2*H]

In [ ]:
N_symbol=[]

N_symbol.append((1-2*x/H)*(1-x/H))
N_symbol.append((4*x/H)*(1-x/H))
N_symbol.append((1-2*x/H)*(-x/H))
N_symbol

[(1 - 0.533333333333333*x)*(1 - 0.266666666666667*x),
 1.06666666666667*x*(1 - 0.266666666666667*x),
 -0.266666666666667*x*(1 - 0.533333333333333*x)]

In [ ]:
B_symbol=[]
for i in range (3):
  B_symbol.append(diff(N_symbol[i],x))
B_symbol

[0.284444444444444*x - 0.8,
 1.06666666666667 - 0.568888888888889*x,
 0.284444444444444*x - 0.266666666666667]

In [ ]:
B_mat=[]
for i in range(3):
  buf=[]
  for j in range(3):
    buf.append(B_symbol[i]*B_symbol[j])
  B_mat.append(buf)
B_mat

[[0.64*(0.355555555555556*x - 1)**2,
  (1.06666666666667 - 0.568888888888889*x)*(0.284444444444444*x - 0.8),
  (0.284444444444444*x - 0.8)*(0.284444444444444*x - 0.266666666666667)],
 [(1.06666666666667 - 0.568888888888889*x)*(0.284444444444444*x - 0.8),
  1.13777777777778*(1 - 0.533333333333333*x)**2,
  (1.06666666666667 - 0.568888888888889*x)*(0.284444444444444*x - 0.266666666666667)],
 [(0.284444444444444*x - 0.8)*(0.284444444444444*x - 0.266666666666667),
  (1.06666666666667 - 0.568888888888889*x)*(0.284444444444444*x - 0.266666666666667),
  0.0809086419753086*(x - 0.9375)**2]]

In [ ]:
k=np.zeros((2,3,3))
f=np.zeros((2,3))

In [ ]:
mat1=[7,-8,1,-8,16,-8,1,-8,7]
#mat2=[-2,-80,49,-80,208,-128,49,-128,79]
nat1=[4,2,-1,2,16,2,-1,2,4]
#nat2=[64,-178,149,-178,496,-418,149,-418,364]
for i in range(3):
  for j in range(3):
    k[0][i][j]=S*K/3/H*mat1[i*3+j]+a_g*P*nat1[i*3+j]/30*H
k[1]=k[0]
k[1][2][2]+=a_g*P*nat1[2*3+2]/30*H
k

array([[[ 172.15927742, -145.1415806 ,   12.25221135],
        [-145.1415806 ,  447.36279387, -145.1415806 ],
        [  12.25221135, -145.1415806 ,  172.15927742]],

       [[ 172.15927742, -145.1415806 ,   12.25221135],
        [-145.1415806 ,  447.36279387, -145.1415806 ],
        [  12.25221135, -145.1415806 ,  203.57520395]]])

In [ ]:
K_glob=np.zeros((5,5))
for i in range(3):
  for j in range(3):
    K_glob[i][j]+=k[0][i][j]
    K_glob[i+2][j+2]+=k[1][i][j]
for j in range(5):
    K_glob[0][j]=0
    #K_glob[j][0]=0
K_glob[0][0]=1
df = pd.DataFrame(K_glob)
print(df)

            0           1           2           3           4
0    1.000000    0.000000    0.000000    0.000000    0.000000
1 -145.141581  447.362794 -145.141581    0.000000    0.000000
2   12.252211 -145.141581  344.318555 -145.141581   12.252211
3    0.000000    0.000000 -145.141581  447.362794 -145.141581
4    0.000000    0.000000   12.252211 -145.141581  203.575204


In [ ]:
n1=[1,4,1]

for i in range(3):
  f[0][i]=a_g*P*T_g*H/6*n1[i]
f[1]=f[0]
f[1][2]+=a_g*P*T_g*H/6*n1[2]
f

array([[1570.79632679, 6283.18530718, 1570.79632679],
       [1570.79632679, 6283.18530718, 3141.59265359]])

In [ ]:
F_glob=np.zeros(5)
for j in range(3):
    F_glob[j]+=f[0][j]
    F_glob[j+2]+=f[1][j]
F_glob[0]=150
F_glob

array([ 150.        , 6283.18530718, 3141.59265359, 6283.18530718,
       3141.59265359])

In [ ]:
T=np.linalg.inv(K_glob)@F_glob
T

array([150.        ,  80.91119505,  56.09857522,  47.03708816,
        45.59149737])