In [ ]:
import math
import numpy as np
import pandas as pd
from sympy import diff, symbols
from scipy import integrate
import sympy as sym
x = symbols('x')

In [ ]:
T_q=150
a_g=10
T_g=40
K=72
L=7.5
R=1
H=L/2
S=math.pi*R**2
P=2*math.pi*R

In [ ]:
psi=[-0.861136, 0.861136, -0.339981, 0.339981]
w=[0.347855,0.347855, 0.652145, 0.652145]
J=H/2

In [ ]:
N_symbol=[]

N_symbol.append(-9/16*(1/9-x**2)*(1-x))
N_symbol.append(27/16*(1/3-x)*(1-x**2))
N_symbol.append(27/16*(1/3+x)*(1-x**2))
N_symbol.append(-9/16*(1/9-x**2)*(1+x))
N_symbol

[(1 - x)*(0.5625*x**2 - 0.0625),
 (0.5625 - 1.6875*x)*(1 - x**2),
 (1 - x**2)*(1.6875*x + 0.5625),
 (x + 1)*(0.5625*x**2 - 0.0625)]

In [ ]:
N_mat=[]
for i in range(4):
  buf=[]
  for j in range(4):
    buf.append(N_symbol[i]*N_symbol[j]*J)
  N_mat.append(buf)
N_mat

[[0.59326171875*(1 - x)**2*(x**2 - 0.111111111111111)**2,
  1.875*(0.5625 - 1.6875*x)*(1 - x)*(1 - x**2)*(0.5625*x**2 - 0.0625),
  1.875*(1 - x)*(1 - x**2)*(1.6875*x + 0.5625)*(0.5625*x**2 - 0.0625),
  0.59326171875*(1 - x)*(x + 1)*(x**2 - 0.111111111111111)**2],
 [1.875*(0.5625 - 1.6875*x)*(1 - x)*(1 - x**2)*(0.5625*x**2 - 0.0625),
  5.33935546875*(0.333333333333333 - x)**2*(1 - x**2)**2,
  1.875*(0.5625 - 1.6875*x)*(1 - x**2)**2*(1.6875*x + 0.5625),
  1.875*(0.5625 - 1.6875*x)*(1 - x**2)*(x + 1)*(0.5625*x**2 - 0.0625)],
 [1.875*(1 - x)*(1 - x**2)*(1.6875*x + 0.5625)*(0.5625*x**2 - 0.0625),
  1.875*(0.5625 - 1.6875*x)*(1 - x**2)**2*(1.6875*x + 0.5625),
  5.33935546875*(1 - x**2)**2*(x + 0.333333333333333)**2,
  1.875*(1 - x**2)*(x + 1)*(1.6875*x + 0.5625)*(0.5625*x**2 - 0.0625)],
 [0.59326171875*(1 - x)*(x + 1)*(x**2 - 0.111111111111111)**2,
  1.875*(0.5625 - 1.6875*x)*(1 - x**2)*(x + 1)*(0.5625*x**2 - 0.0625),
  1.875*(1 - x**2)*(x + 1)*(1.6875*x + 0.5625)*(0.5625*x**2 - 0.0625),
  0

In [ ]:
N_solve=np.zeros((4,4))
for i in range(4):
  for j in range(4):
    for k in range(4):
      N_solve[i][j]+=N_mat[i][j].subs({x:psi[k]})*w[k]
N_solve

array([[ 0.28571384,  0.22098237, -0.08035719,  0.04241075],
       [ 0.22098237,  1.44642904, -0.18080399, -0.08035719],
       [-0.08035719, -0.18080399,  1.44642904,  0.22098237],
       [ 0.04241075, -0.08035719,  0.22098237,  0.28571384]])

In [ ]:
B_symbol=[]
for i in range (4):
  B_symbol.append(diff(N_symbol[i],x)*2/H)
B_symbol

[-0.3*x**2 + 0.6*x*(1 - x) + 0.0333333333333333,
 0.9*x**2 - 1.06666666666667*x*(0.5625 - 1.6875*x) - 0.9,
 -0.9*x**2 - 1.06666666666667*x*(1.6875*x + 0.5625) + 0.9,
 0.3*x**2 + 0.6*x*(x + 1) - 0.0333333333333333]

In [ ]:
B_mat=[]
for i in range(4):
  buf=[]
  for j in range(4):
    buf.append(B_symbol[i]*B_symbol[j]*J)
  B_mat.append(buf)
B_mat

[[0.675*(-0.5*x**2 + x*(1 - x) + 0.0555555555555556)**2,
  1.875*(-0.3*x**2 + 0.6*x*(1 - x) + 0.0333333333333333)*(0.9*x**2 - 1.06666666666667*x*(0.5625 - 1.6875*x) - 0.9),
  1.875*(-0.9*x**2 - 1.06666666666667*x*(1.6875*x + 0.5625) + 0.9)*(-0.3*x**2 + 0.6*x*(1 - x) + 0.0333333333333333),
  1.875*(-0.3*x**2 + 0.6*x*(1 - x) + 0.0333333333333333)*(0.3*x**2 + 0.6*x*(x + 1) - 0.0333333333333333)],
 [1.875*(-0.3*x**2 + 0.6*x*(1 - x) + 0.0333333333333333)*(0.9*x**2 - 1.06666666666667*x*(0.5625 - 1.6875*x) - 0.9),
  2.13333333333333*(0.84375*x**2 - x*(0.5625 - 1.6875*x) - 0.84375)**2,
  1.875*(-0.9*x**2 - 1.06666666666667*x*(1.6875*x + 0.5625) + 0.9)*(0.9*x**2 - 1.06666666666667*x*(0.5625 - 1.6875*x) - 0.9),
  1.875*(0.3*x**2 + 0.6*x*(x + 1) - 0.0333333333333333)*(0.9*x**2 - 1.06666666666667*x*(0.5625 - 1.6875*x) - 0.9)],
 [1.875*(-0.9*x**2 - 1.06666666666667*x*(1.6875*x + 0.5625) + 0.9)*(-0.3*x**2 + 0.6*x*(1 - x) + 0.0333333333333333),
  1.875*(-0.9*x**2 - 1.06666666666667*x*(1.6875*x + 0.56

In [ ]:
B_solve=np.zeros((4,4))
for i in range(4):
  for j in range(4):
    for k in range(4):
      B_solve[i][j]+=B_mat[i][j].subs({x:psi[k]})*w[k]
B_solve

array([[ 0.98666594, -1.25999841,  0.35999871, -0.08666624],
       [-1.25999841,  2.87999642, -1.97999672,  0.35999871],
       [ 0.35999871, -1.97999672,  2.87999642, -1.25999841],
       [-0.08666624,  0.35999871, -1.25999841,  0.98666594]])

In [ ]:
k=np.zeros((2,4,4))
f=np.zeros((2,4))

In [ ]:
for i in range(4):
  for j in range(4):
    k[0][i][j]=S*K*B_solve[i][j]+a_g*P*N_solve[i][j]
k[1]=k[0]
k[1][3][3]+=a_g*S
k

array([[[ 241.13050806, -271.12019518,   76.38079866,  -16.93869487],
        [-271.12019518,  742.32165999, -459.22495563,   76.38079866],
        [  76.38079866, -459.22495563,  742.32165999, -271.12019518],
        [ -16.93869487,   76.38079866, -271.12019518,  241.13050806]],

       [[ 241.13050806, -271.12019518,   76.38079866,  -16.93869487],
        [-271.12019518,  742.32165999, -459.22495563,   76.38079866],
        [  76.38079866, -459.22495563,  742.32165999, -271.12019518],
        [ -16.93869487,   76.38079866, -271.12019518,  272.5464346 ]]])

In [ ]:
K_glob=np.zeros((7,7))
for i in range(4):
  for j in range(4):
    K_glob[i][j]+=k[0][i][j]
    K_glob[i+3][j+3]+=k[1][i][j]
for j in range(7):
    K_glob[0][j]=0
K_glob[0][0]=1
df = pd.DataFrame(K_glob)
print(df)

            0           1           2           3           4           5  \
0    1.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
1 -271.120195  742.321660 -459.224956   76.380799    0.000000    0.000000   
2   76.380799 -459.224956  742.321660 -271.120195    0.000000    0.000000   
3  -16.938695   76.380799 -271.120195  482.261016 -271.120195   76.380799   
4    0.000000    0.000000    0.000000 -271.120195  742.321660 -459.224956   
5    0.000000    0.000000    0.000000   76.380799 -459.224956  742.321660   
6    0.000000    0.000000    0.000000  -16.938695   76.380799 -271.120195   

            6  
0    0.000000  
1    0.000000  
2    0.000000  
3  -16.938695  
4   76.380799  
5 -271.120195  
6  272.546435  


In [ ]:
sym.integrate(N_symbol[i], (x, -1, 1))

0.250000000000000

In [ ]:
n_solve=np.zeros((4))
for i in range(4):
  for k in range(4):
    n_solve[i]+=(N_symbol[i]*J).subs({x:psi[k]})*w[k]
n_solve

array([0.46874977, 1.40625023, 1.40625023, 0.46874977])

In [ ]:
n_solve=np.zeros((4))
for i in range(4):
  for k in range(4):
    n_solve[i]=sym.integrate(N_symbol[i]*J, (x, -1, 1))
n_solve

array([0.46875, 1.40625, 1.40625, 0.46875])

In [ ]:
for i in range(4):
  f[0][i]=a_g*P*T_g*n_solve[i]
f[1]=f[0]
f[1][3]+=a_g*S*T_g
f

array([[1178.0972451 , 3534.29173529, 3534.29173529, 1178.0972451 ],
       [1178.0972451 , 3534.29173529, 3534.29173529, 2434.73430653]])

In [ ]:
F_glob=np.zeros(7)
for j in range(4):
    F_glob[j]+=f[0][j]
    F_glob[j+3]+=f[1][j]
F_glob[0]=150
F_glob

array([ 150.        , 3534.29173529, 3534.29173529, 2356.19449019,
       3534.29173529, 3534.29173529, 2434.73430653])

In [ ]:
T=np.linalg.inv(K_glob)@F_glob
T

array([150.        ,  96.81016329,  69.45041766,  55.3988036 ,
        48.18848558,  44.70035851,  43.33798262])