In [ ]:
import math
import numpy as np
import pandas as pd

In [ ]:
def init_B(B, Y, X, z, S):
	b = [Y[1] - Y[2], Y[2] - Y[0], Y[0] - Y[1]]
	c = [X[2] - X[1], X[0] - X[2], X[1] - X[0]]
	buf =[ [b[0], 0, b[1], 0, b[2], 0], [ 0, c[0], 0, c[1], 0, c[2] ], [ c[0], b[0], c[1], b[1], c[2], b[2] ] ]
	for i in range(3):
		for j in range(6):
			B[z][i][j] = buf[i][j]/(2*S)

def print_N(Y, X, S):
	b = [Y[1] - Y[2], Y[2] - Y[0], Y[0] - Y[1]]
	c = [X[2] - X[1], X[0] - X[2], X[1] - X[0]]
	a = [X[1]*Y[2] - X[2]*Y[1], X[2]*Y[0] - X[0]*Y[2], X[0]*Y[1] - X[1]*Y[0]]
	for i in range(3): print(a[i]/(2*S), b[i]/(2*S),c[i]/(2*S))

In [ ]:
E=6*10**6
mu=0.25
F=20
t=2
S=9/2

In [ ]:
B = []
for i in range(4):
  Buf=[]
  for j in range(3):
    Buf.append([0]*6)
  B.append(Buf)
D = [ [0]*3 for i in range(3) ]

In [ ]:
buf1=[1,mu, 0,mu,1,0,0,0,(1-mu)/2]
for i in range(3):
  for j in range(3):
    D[i][j]=buf1[i*3+j]*E/(1-mu**2)
D

[[6400000.0, 1600000.0, 0.0],
 [1600000.0, 6400000.0, 0.0],
 [0.0, 0.0, 2400000.0]]

In [ ]:
X = [[0,3,0], [0,3,3], [3,6,3], [3,6,6]]
Y = [[0,0,3], [3,0,3], [0,0,3], [3,0,3]]

In [ ]:
for z in range(4):
  init_B(B,Y[z],X[z],z, S)
B

[[[-0.3333333333333333, 0.0, 0.3333333333333333, 0.0, 0.0, 0.0],
  [0.0, -0.3333333333333333, 0.0, 0.0, 0.0, 0.3333333333333333],
  [-0.3333333333333333,
   -0.3333333333333333,
   0.0,
   0.3333333333333333,
   0.3333333333333333,
   0.0]],
 [[-0.3333333333333333, 0.0, 0.0, 0.0, 0.3333333333333333, 0.0],
  [0.0, 0.0, 0.0, -0.3333333333333333, 0.0, 0.3333333333333333],
  [0.0,
   -0.3333333333333333,
   -0.3333333333333333,
   0.0,
   0.3333333333333333,
   0.3333333333333333]],
 [[-0.3333333333333333, 0.0, 0.3333333333333333, 0.0, 0.0, 0.0],
  [0.0, -0.3333333333333333, 0.0, 0.0, 0.0, 0.3333333333333333],
  [-0.3333333333333333,
   -0.3333333333333333,
   0.0,
   0.3333333333333333,
   0.3333333333333333,
   0.0]],
 [[-0.3333333333333333, 0.0, 0.0, 0.0, 0.3333333333333333, 0.0],
  [0.0, 0.0, 0.0, -0.3333333333333333, 0.0, 0.3333333333333333],
  [0.0,
   -0.3333333333333333,
   -0.3333333333333333,
   0.0,
   0.3333333333333333,
   0.3333333333333333]]]

In [ ]:
print_N(Y[3], X[3], S)

2.0 -0.3333333333333333 0.0
1.0 0.0 -0.3333333333333333
-2.0 0.3333333333333333 0.3333333333333333


In [ ]:
K=[]
for i in range(4):
  ans = np.dot(np.transpose(B[i]), D)
  K.append(np.dot(ans, B[i])*t*S)
K

[array([[ 8800000.,  4000000., -6400000., -2400000., -2400000., -1600000.],
        [ 4000000.,  8800000., -1600000., -2400000., -2400000., -6400000.],
        [-6400000., -1600000.,  6400000.,        0.,        0.,  1600000.],
        [-2400000., -2400000.,        0.,  2400000.,  2400000.,        0.],
        [-2400000., -2400000.,        0.,  2400000.,  2400000.,        0.],
        [-1600000., -6400000.,  1600000.,        0.,        0.,  6400000.]]),
 array([[ 6400000.,        0.,        0.,  1600000., -6400000., -1600000.],
        [       0.,  2400000.,  2400000.,        0., -2400000., -2400000.],
        [       0.,  2400000.,  2400000.,        0., -2400000., -2400000.],
        [ 1600000.,        0.,        0.,  6400000., -1600000., -6400000.],
        [-6400000., -2400000., -2400000., -1600000.,  8800000.,  4000000.],
        [-1600000., -2400000., -2400000., -6400000.,  4000000.,  8800000.]]),
 array([[ 8800000.,  4000000., -6400000., -2400000., -2400000., -1600000.],
        

In [ ]:
F=[0,0,0,0,0,0, 0,0,6000000,0,6000000,0] #!!!

In [ ]:
nodes =[ 1,3,2, 2,3,4, 3,5,4, 4,5,6 ];
K_glob=[[0]*12 for i in range(12)]

ind=0
for z in range(0, 12, 3):
	K_glob[(nodes[z] - 1)*2][(nodes[z] - 1)*2] += round(K[ind][0][0],2)
	K_glob[(nodes[z + 1] - 1)*2][(nodes[z + 1] - 1)*2] += round(K[ind][2][2],2)
	K_glob[(nodes[z + 2] - 1)*2][(nodes[z + 2] - 1)*2] += round(K[ind][4][4],2)

	K_glob[(nodes[z + 1] - 1)*2][(nodes[z] - 1)*2] += round(K[ind][2][0],2)
	K_glob[(nodes[z] - 1)*2][(nodes[z + 1] - 1)*2] += round(K[ind][0][2],2)

	K_glob[(nodes[z + 2] - 1)*2][(nodes[z] - 1)*2] += round(K[ind][4][0],2)
	K_glob[(nodes[z] - 1)*2][(nodes[z + 2] - 1)*2] += round(K[ind][0][4],2)

	K_glob[(nodes[z + 1] - 1)*2][(nodes[z + 2] - 1)*2] += round(K[ind][2][4],2)
	K_glob[(nodes[z + 2] - 1)*2][(nodes[z + 1] - 1)*2] += round(K[ind][4][2],2)

	ind+=1

ind=0
for z in range(0, 12, 3):
	K_glob[(nodes[z] - 1)*2+1][(nodes[z] - 1)*2+1] += round(K[ind][1][1],2)
	K_glob[(nodes[z + 1] - 1)*2+1][(nodes[z + 1] - 1)*2+1] += round(K[ind][3][3],2)
	K_glob[(nodes[z + 2] - 1)*2+1][(nodes[z + 2] - 1)*2+1] += round(K[ind][5][5],2)

	K_glob[(nodes[z + 1] - 1)*2+1][(nodes[z] - 1)*2+1] += round(K[ind][3][1],2)
	K_glob[(nodes[z] - 1)*2+1][(nodes[z + 1] - 1)*2+1] += round(K[ind][1][3],2)

	K_glob[(nodes[z + 2] - 1)*2+1][(nodes[z] - 1)*2+1] += round(K[ind][5][1],2)
	K_glob[(nodes[z] - 1)*2+1][(nodes[z + 2] - 1)*2+1] += round(K[ind][1][5],2)

	K_glob[(nodes[z + 1] - 1)*2+1][(nodes[z + 2] - 1)*2+1] += round(K[ind][3][5],2)
	K_glob[(nodes[z + 2] - 1)*2+1][(nodes[z + 1] - 1)*2+1] += round(K[ind][5][3],2)

	ind+=1

ind=0
for z in range(0, 12, 3):
	K_glob[(nodes[z] - 1)*2][(nodes[z] - 1)*2+1] += round(K[ind][0][1],2)
	K_glob[(nodes[z] - 1)*2+1][(nodes[z] - 1)*2] += round(K[ind][1][0],2)

	K_glob[(nodes[z] - 1)*2][(nodes[z + 1] - 1)*2+1] += round(K[ind][0][3],2)
	K_glob[(nodes[z + 1] - 1)*2+1][(nodes[z] - 1)*2] += round(K[ind][3][0],2)

	K_glob[(nodes[z] - 1)*2][(nodes[z + 2] - 1)*2+1] += round(K[ind][0][5],2)
	K_glob[(nodes[z + 2] - 1)*2+1][(nodes[z] - 1)*2] += round(K[ind][5][0],2)

	K_glob[(nodes[z] - 1)*2+1][(nodes[z + 1] - 1)*2] += round(K[ind][1][2],2)
	K_glob[(nodes[z + 1] - 1)*2][(nodes[z] - 1)*2+1] += round(K[ind][2][1],2)

	K_glob[(nodes[z] - 1)*2+1][(nodes[z + 2] - 1)*2] += round(K[ind][1][4],2)
	K_glob[(nodes[z + 2] - 1)*2][(nodes[z] - 1)*2+1] += round(K[ind][4][1],2)

	K_glob[(nodes[z + 1] - 1)*2][(nodes[z + 1] - 1)*2+1] += round(K[ind][2][3],2)
	K_glob[(nodes[z + 1] - 1)*2+1][(nodes[z + 1] - 1)*2] += round(K[ind][3][2],2)

	K_glob[(nodes[z + 1] - 1)*2][(nodes[z + 2] - 1)*2+1] += round(K[ind][2][5],2)
	K_glob[(nodes[z + 2] - 1)*2+1][(nodes[z + 1] - 1)*2] += round(K[ind][5][2],2)

	K_glob[(nodes[z + 1] - 1)*2+1][(nodes[z + 2] - 1)*2] += round(K[ind][3][4],2)
	K_glob[(nodes[z + 2] - 1)*2][(nodes[z + 1] - 1)*2+1] += round(K[ind][4][3],2)

	K_glob[(nodes[z + 2] - 1)*2][(nodes[z + 2] - 1)*2+1] += round(K[ind][4][5],2)
	K_glob[(nodes[z + 2] - 1)*2+1][(nodes[z + 2] - 1)*2] += round(K[ind][5][4],2)

	ind+=1

#df = pd.DataFrame(K_glob)
#print(df)

In [ ]:
for i in range(12):
  K_glob[0][i] = 0
  K_glob[1][i] = 0
  K_glob[2][i] = 0
  K_glob[3][i] = 0
K_glob[0][0] = 10000000 #!!!
K_glob[1][1] = 10000000
K_glob[2][2] = 10000000
K_glob[3][3] = 10000000

df = pd.DataFrame(K_glob)
print(df)

            0           1           2           3           4           5   \
0   10000000.0         0.0         0.0         0.0         0.0         0.0   
1          0.0  10000000.0         0.0         0.0         0.0         0.0   
2          0.0         0.0  10000000.0         0.0         0.0         0.0   
3          0.0         0.0         0.0  10000000.0         0.0         0.0   
4   -6400000.0  -1600000.0         0.0   4000000.0  17600000.0   4000000.0   
5   -2400000.0  -2400000.0   4000000.0         0.0   4000000.0  17600000.0   
6          0.0         0.0  -6400000.0  -2400000.0  -4800000.0  -4000000.0   
7          0.0         0.0  -1600000.0  -2400000.0  -4000000.0 -12800000.0   
8          0.0         0.0         0.0         0.0  -6400000.0  -1600000.0   
9          0.0         0.0         0.0         0.0  -2400000.0  -2400000.0   
10         0.0         0.0         0.0         0.0         0.0         0.0   
11         0.0         0.0         0.0         0.0         0.0  

In [ ]:
np.linalg.inv(K_glob)@F

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.91290146,
        0.06559612,  1.02222832, -0.17492298,  1.90963493, -0.0413406 ,
        2.02294536, -0.29062356])